export const CITY_REQUEST = "CITY_REQUEST";
export const CITY_SUCCESS = "CITY_SUCCESS";
export const CITY_ERROR = "CITY_ERROR";

export const ALL_CITY_REQUEST = "ALL_CITY_REQUEST";
export const ALL_CITY_SUCCESS = "ALL_CITY_SUCCESS";
export const ALL_CITY_ERROR = "ALL_CITY_ERROR";

export const CITY_DETAILS_REQUEST = "CITY_DETAILS_REQUEST";
export const CITY_DETAILS_SUCCESS = "CITY_DETAILS_SUCCESS";
export const CITY_DETAILS_ERROR = "CITY_DETAILS_ERROR";