
export const ALL_COMMENT_OF_REVIEW_REQUEST = "ALL_COMMENT_OF_REVIEW_REQUEST";
export const ALL_COMMENT_OF_REVIEW_SUCCESS = "ALL_COMMENT_OF_REVIEW_SUCCESS";
export const ALL_COMMENT_OF_REVIEW_ERROR = "ALL_COMMENT_OF_REVIEW_ERROR";

export const COMMENT_DETAILS_REQUEST = "COMMENT_DETAILS_REQUEST";
export const COMMENT_DETAILS_SUCCESS = "COMMENT_DETAILS_SUCCESS";
export const COMMENT_DETAILS_ERROR = "COMMENT_DETAILS_ERROR";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_ERROR = "UPDATE_COMMENT_ERROR";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

