export const OBJECT_REQUEST = "OBJECT_REQUEST";
export const OBJECT_SUCCESS = "OBJECT_SUCCESS";
export const OBJECT_ERROR = "OBJECT_ERROR";

export const ALL_OBJECT_OF_CITY_REQUEST = "ALL_OBJECT_OF_CITY_REQUEST";
export const ALL_OBJECT_OF_CITY_SUCCESS = "ALL_OBJECT_OF_CITY_SUCCESS";
export const ALL_OBJECT_OF_CITY_ERROR = "ALL_OBJECT_OF_CITY_ERROR";

export const ALL_OBJECT_OF_USER_REQUEST = "ALL_OBJECT_OF_CITY_REQUEST";
export const ALL_OBJECT_OF_USER_SUCCESS = "ALL_OBJECT_OF_CITY_SUCCESS";
export const ALL_OBJECT_OF_USER_ERROR = "ALL_OBJECT_OF_CITY_ERROR";

export const ALL_OBJECT_REQUEST = "ALL_OBJECT_REQUEST";
export const ALL_OBJECT_SUCCESS = "ALL_OBJECT_SUCCESS";
export const ALL_OBJECT_ERROR = "ALL_OBJECT_ERROR";

export const OBJECT_DETAILS_REQUEST = "OBJECT_DETAILS_REQUEST";
export const OBJECT_DETAILS_SUCCESS = "OBJECT_DETAILS_SUCCESS";
export const OBJECT_DETAILS_ERROR = "OBJECT_DETAILS_ERROR";

export const CREATE_OBJECT_REQUEST = "CREATE_OBJECT_REQUEST";
export const CREATE_OBJECT_SUCCESS = "CREATE_OBJECT_SUCCESS";
export const CREATE_OBJECT_ERROR = "CREATE_OBJECT_ERROR";

export const UPDATE_OBJECT_REQUEST = "UPDATE_OBJECT_REQUEST";
export const UPDATE_OBJECT_SUCCESS = "UPDATE_OBJECT_SUCCESS";
export const UPDATE_OBJECT_ERROR = "UPDATE_OBJECT_ERROR";

export const DELETE_OBJECT_REQUEST = "DELETE_OBJECT_REQUEST";
export const DELETE_OBJECT_SUCCESS = "DELETE_OBJECT_SUCCESS";
export const DELETE_OBJECT_ERROR = "DELETE_OBJECT_ERROR";

