export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_ERROR = "REVIEW_ERROR";

export const ALL_REVIEW_OF_OBJECT_REQUEST = "ALL_REVIEW_OF_OBJECT_REQUEST";
export const ALL_REVIEW_OF_OBJECT_SUCCESS = "ALL_REVIEW_OF_OBJECT_SUCCESS";
export const ALL_REVIEW_OF_OBJECT_ERROR = "ALL_REVIEW_OF_OBJECT_ERROR";

export const ALL_REVIEW_OF_USER_REQUEST = "ALL_REVIEW_OF_USER_REQUEST";
export const ALL_REVIEW_OF_USER_SUCCESS = "ALL_REVIEW_OF_USER_SUCCESS";
export const ALL_REVIEW_OF_USER_ERROR = "ALL_REVIEW_OF_USER_ERROR";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_ERROR = "ALL_REVIEW_ERROR";

export const REVIEW_DETAILS_REQUEST = "REVIEW_DETAILS_REQUEST";
export const REVIEW_DETAILS_SUCCESS = "REVIEW_DETAILS_SUCCESS";
export const REVIEW_DETAILS_ERROR = "REVIEW_DETAILS_ERROR";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_ERROR = "CREATE_REVIEW_ERROR";

export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_ERROR = "UPDATE_REVIEW_ERROR";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_ERROR = "DELETE_REVIEW_ERROR";

