export const SEARCH_CITY_REQUEST = "SEARCH_CITY_REQUEST";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_ERROR = "SEARCH_CITY_ERROR";

export const SEARCH_OBJECT_REQUEST = "SEARCH_OBJECT_REQUEST";
export const SEARCH_OBJECT_SUCCESS = "SEARCH_OBJECT_SUCCESS";
export const SEARCH_OBJECT_ERROR = "SEARCH_OBJECT_ERROR";

export const SEARCH_BLOG_REQUEST = "SEARCH_BLOG_REQUEST";
export const SEARCH_BLOG_SUCCESS = "SEARCH_BLOG_SUCCESS";
export const SEARCH_BLOG_ERROR = "SEARCH_BLOG_ERROR";

